## Importing Libraries

In [17]:
#Importing Important Libraries
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Loading the data set

In [4]:
df = pd.read_csv('/Users/GHOST/Desktop/iris dataset.csv')
df
#You can load this through the dataset library from sklearn import datasets
#all the measurements are in cm

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
#Columns of our dataset
print(df.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')


In [7]:
#How many variety we have of flowers
df['variety'].value_counts()

Virginica     50
Versicolor    50
Setosa        50
Name: variety, dtype: int64

## Normalize the data and display

In [8]:
# Splitting the data in X and y
iris_data = df.values
X = iris_data[:,0:4].astype(float)
y = iris_data[:,4]

In [36]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
print(y)
# As we can see our 'y' dataset is the only data which is not same as X

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'V

In [14]:
# We will use label encoder to normalize the data
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [11]:
#Encoded the string into the numbers through one label encoder
#these are used to fill missing values and labeling 
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
#converted y1 data into the matrices
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [22]:
from sklearn.model_selection import train_test_split
#train 60
#test 40
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.40, random_state = 0)

## Splitted our data into the training and testing 

In [29]:
print(x_train.shape)

(90, 4)


In [30]:
print(x_test.shape)

(60, 4)


In [31]:
print(y_train.shape)

(90, 3)


In [32]:
print(y_test.shape)

(60, 3)


## Building a Neural Network 

In [23]:
model = Sequential()
model.add(Dense(4, input_dim =4, activation = 'relu'))
model.add(Dense(5, activation = 'relu' ))
model.add(Dense(3, activation = 'softmax'))
#For minority classes we can also go for sigmoid activation in the output layer

In [24]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 18        
Total params: 63
Trainable params: 63
Non-trainable params: 0
_________________________________________________________________


In [33]:
#Initial Weight
print(model.get_weights())

[array([[ 0.57840294, -0.3660063 , -0.19446766,  0.10284656],
       [-0.06557506,  0.70755345,  0.15639418,  0.3815232 ],
       [-0.82237566,  0.77756673, -0.42660946, -0.6803305 ],
       [ 0.749572  , -0.28742486,  0.2418117 ,  0.7200783 ]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[ 0.5795853 , -0.3581801 ,  0.063752  ,  0.12807924,  0.756371  ],
       [ 0.10922003, -0.6986911 ,  0.7899581 ,  0.04437965,  0.7559849 ],
       [ 0.6340172 ,  0.07121265,  0.10661829,  0.6856624 , -0.19572657],
       [ 0.6658937 ,  0.00681841, -0.22705156,  0.06907499, -0.09223038]],
      dtype=float32), array([0., 0., 0., 0., 0.], dtype=float32), array([[ 0.78861696, -0.2845261 , -0.81336683],
       [ 0.00399244,  0.04229653,  0.21333319],
       [ 0.86565083,  0.1637004 ,  0.03180873],
       [ 0.47069627,  0.6602668 , -0.09106278],
       [-0.7109745 , -0.8446392 , -0.54882497]], dtype=float32), array([0., 0., 0.], dtype=float32)]


In [35]:
#Train Our model on train data
model.fit(x_train, y_train, epochs = 50, batch_size = 8)

Epoch 1/50
12/12 [==============================] - 0s 819us/step - loss: 0.6119 - accuracy: 0.7000
Epoch 2/50
12/12 [==============================] - 0s 819us/step - loss: 0.6056 - accuracy: 0.7000
Epoch 3/50
12/12 [==============================] - 0s 819us/step - loss: 0.5999 - accuracy: 0.7000
Epoch 4/50
12/12 [==============================] - 0s 819us/step - loss: 0.5935 - accuracy: 0.7000
Epoch 5/50
12/12 [==============================] - 0s 819us/step - loss: 0.5888 - accuracy: 0.7000
Epoch 6/50
12/12 [==============================] - 0s 728us/step - loss: 0.5827 - accuracy: 0.7000
Epoch 7/50
12/12 [==============================] - 0s 819us/step - loss: 0.5774 - accuracy: 0.7000
Epoch 8/50
12/12 [==============================] - 0s 728us/step - loss: 0.5722 - accuracy: 0.7000
Epoch 9/50
12/12 [==============================] - 0s 819us/step - loss: 0.5667 - accuracy: 0.7111
Epoch 10/50
12/12 [==============================] - 0s 728us/step - loss: 0.5618 - accuracy: 0.7111